allowBuilds:
  '@prisma/engines': true
  core-js: true
  esbuild: true
  prisma: true
  sharp: true

onlyBuiltDependencies:
  - '@prisma/engines'
  - core-js
  - esbuild
  - prisma
  - sharp

overrides:
  hono: 4.12.25
